### ISSUE TITLE
error: /AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-6     

### ISSUE THREAD

**Issue by Proxcentaur** [zhengchun/LocalVPN-Kotlin#2]
Hi i just cloned your localVPN-Kotlin git, but I got this error:
E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-6
    Process: org.kotlin.examples.localvpn, PID: 22041
    kotlin.KotlinNullPointerException
        at org.kotlin.examples.localvpn.TcpVpnService.serveOutput(TcpVpnService.kt:282)
        at org.kotlin.examples.localvpn.TcpVpnService$start$1$1$1$1.doResume(TcpVpnService.kt:45)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(ForkJoinPool.java:1112)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1156)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

this error come up whenever I tried to access browser e.g chrome. not only browser but youtube too
any sugesstion?

**Comment by Proxcentaur** [comment]
it has been stopped working whenever hit an URL

**Comment by zhengchun** [comment]
Hello, this project is not maintained anymore, It was created for my learning `Kotlin` language, cloned from https://github.com/hexene/LocalVPN/. 

I suggest you to https://stackoverflow.com or another tech community to get help, thanks.
